// Generated by CoffeeScript 1.10.0
var codes, ticks;

ticks = require('sedata').ticks;

codes = "900901,000002sz,600603sh,200429,159915";

ticks(codes, function(obj) {
  var ref, 名稱, 買, 賣5;
  ref = obj.sz159915, 買 = ref.買, 名稱 = ref.名稱, 賣5 = ref.賣5;
  return console.log('here:', 買, 名稱, 賣5);
});

//# sourceMappingURL=example.js.map
