// Generated by CoffeeScript 1.10.0

/*
 Copyright(c) 2016- Jigme Ko <jigme1968@gmail.com>
 MIT Licensed
 */
var hqstr2obj, iconv, recode, ref, request, restring, sinaticks;

ref = require('secode'), restring = ref.restring, recode = ref.recode;

request = require('request');

iconv = require('iconv-lite');

hqstr2obj = function(代碼, tickstr, obj) {
  var c, tick;
  c = recode(代碼, 0);
  tick = (c + "," + tickstr).split(',');
  obj[代碼] = {
    代碼: tick[0],
    名稱: tick[1],
    開: Number(tick[2]),
    收: Number(tick[3]),
    現: Number(tick[4]),
    高: Number(tick[5]),
    低: Number(tick[6]),
    買: Number(tick[7]),
    賣: Number(tick[8]),
    量: Number(tick[9]),
    額: Number(tick[10]),
    買量1: Number(tick[11]),
    買1: Number(tick[12]),
    買量2: Number(tick[13]),
    買2: Number(tick[14]),
    買量3: Number(tick[15]),
    買3: Number(tick[16]),
    買量4: Number(tick[17]),
    買4: Number(tick[18]),
    買量5: Number(tick[19]),
    買5: Number(tick[20]),
    賣量1: Number(tick[21]),
    賣1: Number(tick[22]),
    賣量2: Number(tick[23]),
    賣2: Number(tick[24]),
    賣量3: Number(tick[25]),
    賣3: Number(tick[26]),
    賣量4: Number(tick[27]),
    賣4: Number(tick[28]),
    賣量5: Number(tick[29]),
    賣5: Number(tick[30])
  };
  obj[代碼].時間 = new Date(tick.slice(31, 33).join(' '));
  obj[代碼].備註 = tick[33];
  obj[代碼].市場代碼 = 代碼.slice(0, 2);
  return obj;
};

sinaticks = function(string, callback) {
  var codes, obj, options;
  codes = restring(string, 'sina');
  obj = {};
  options = {
    url: "http://hq.sinajs.cn/list=" + codes,
    json: false,
    encoding: null
  };
  return request(options, function(err, res, data) {
    var i, len, ref1, text, tickstr, 代碼;
    text = iconv.decode(data, 'GBK');
    eval(text);
    ref1 = codes.split(',');
    for (i = 0, len = ref1.length; i < len; i++) {
      代碼 = ref1[i];
      tickstr = eval("hq_str_" + 代碼);
      hqstr2obj(代碼, tickstr, obj);
    }
    return callback(obj);
  });
};

module.exports = {
  ticks: sinaticks
};

//# sourceMappingURL=sedata.js.map
