// Generated by CoffeeScript 1.10.0
var codes, ref, ticks, tsdata;

ref = require('../sedata'), ticks = ref.ticks, tsdata = ref.tsdata;

tsdata({
  func: 'get_hist_data',
  args: "'300388',ktype='W'"
}, function(res) {
  return console.log(res);
});

codes = "900901,000002sz,600603sh,200429,159915";

ticks(codes, function(obj) {
  var ask5, buy, name, ref1;
  ref1 = obj.sz159915, buy = ref1.buy, name = ref1.name, ask5 = ref1.ask5;
  return console.log('here:', buy, name, ask5);
});

//# sourceMappingURL=example.js.map
