// Generated by CoffeeScript 1.10.0
var codes, ref, ticks, tsdata;

ref = require('../sedata'), ticks = ref.ticks, tsdata = ref.tsdata;

tsdata({
  func: 'get_hist_data',
  args: "'300388',ktype='W'"
}, function(res) {
  return console.log(res);
});

codes = "900901,000002sz,600603sh,200429,159915";

ticks(codes, function(obj) {
  var ref1, 名稱, 買, 賣5;
  ref1 = obj.sz159915, 買 = ref1.買, 名稱 = ref1.名稱, 賣5 = ref1.賣5;
  return console.log('here:', 買, 名稱, 賣5);
});

//# sourceMappingURL=example.js.map
