// Generated by CoffeeScript 1.10.0

/*
 Copyright(c) 2016- Jigme Ko <jigme1968@gmail.com>
 MIT Licensed
 */
var hqstr2obj, iconv, request, sinaticks;

request = require('request');

iconv = require('iconv-lite');

hqstr2obj = function(symbol, tickstr, obj) {
  var c, tick;
  c = symbol.slice(4);
  tick = (c + "," + tickstr).split(',');
  obj[symbol] = {
    symbol: tick[0],
    現: Number(tick[2]),
    未知: Number(tick[3]),
    前: Number(tick[4]),
    波幅: Number(tick[5]),
    開: Number(tick[6]),
    高: Number(tick[7]),
    低: Number(tick[8]),
    現: Number(tick[9]),
    名稱: Number(tick[10]),
    漲幅: Number(tick[11]),
    未知: Number(tick[12]),
    振幅: Number(tick[13]),
    近高: Number(tick[15]),
    近低: Number(tick[16])
  };
  obj[symbol].時間 = new Date(tick[18] + " " + tick[1]);
  obj[symbol].備註 = tick[17];
  obj[symbol].報價 = tick[14];
  return obj;
};

sinaticks = function(string, callback) {
  var codes, each, obj, options;
  codes = ((function() {
    var i, len, ref, results;
    ref = string.split(',');
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      each = ref[i];
      results.push("fx_s" + each);
    }
    return results;
  })()).join(',');
  obj = {};
  options = {
    url: "http://hq.sinajs.cn/list=" + codes,
    json: false,
    encoding: null
  };
  return request(options, function(err, res, data) {
    var i, len, ref, symbol, text, tickstr;
    if (err) {
      console.error(err);
    }
    if (err == null) {
      text = iconv.decode(data, 'GBK');
      eval(text);
      ref = codes.split(',');
      for (i = 0, len = ref.length; i < len; i++) {
        symbol = ref[i];
        tickstr = eval("hq_str_" + symbol);
        hqstr2obj(symbol, tickstr, obj);
      }
      return callback(obj);
    }
  });
};

module.exports = sinaticks;

//# sourceMappingURL=forex.js.map
