// Generated by CoffeeScript 1.10.0
var history, recode, ref, request, restring;

request = require('request');

ref = require('secode'), recode = ref.recode, restring = ref.restring;


/* param:
      market: 默認 hs--滬深
      symbol: 代碼
      year: 年份
      type: day,week,month
 */

history = function(param, callback) {
  var c, host, l, options, ref1, scale, t, url;
  if (param.symbol.length < 5) {
    return callback('代碼不對', null);
  }
  scale = {
    m05: 5,
    m15: 15,
    m30: 30,
    m60: 60,
    day: 60 * 4,
    week: 60 * 4 * 5
  };
  host = "http://money.finance.sina.com.cn/quotes_service/api/json_v2.php";
  c = recode(param.symbol, 1);
  t = scale[param.type];
  l = (ref1 = param.len) != null ? ref1 : 0;
  url = host + "/CN_MarketData.getKLineData?symbol=" + c + "&scale=" + t + "&datalen=" + l;
  options = {
    url: url,
    json: false
  };
  return request.get(options, function(err, res, string) {
    var arr, each, error, error1, i, len;
    if (err == null) {
      try {
        arr = eval(string);
      } catch (error1) {
        error = error1;
        callback(error, null);
      }
      if (arr) {
        for (i = 0, len = arr.length; i < len; i++) {
          each = arr[i];
          each.day = new Date(each.day);
          each.open = Number(each.open);
          each.low = Number(each.low);
          each.high = Number(each.high);
          each.close = Number(each.close);
          each.volume = Number(each.volume);
        }
      }
    }
    return callback(err, arr);
  });
};

module.exports = history;


/* 在這行前面加或去一個#就可以測試,測試完記得加回去
history {symbol:'150152',type:'week'},(err, arr)->
  console.log arr
 */

//# sourceMappingURL=jsonsina.js.map
