// Generated by CoffeeScript 1.10.0
var history, iconv, recode, ref, request, restring;

request = require('request');

iconv = require('iconv-lite');

ref = require('secode'), recode = ref.recode, restring = ref.restring;


/* param:
      market: 默認 hs--滬深
      code: 代碼
      year: 年份
      type: day,week,month
 */

history = function(param, callback) {
  var c, options, url;
  c = recode(param.code, 6);
  url = "http://img1.money.126.net/data/" + param.market + "/kline/" + param.type + "/history/" + param.year + "/" + c + ".json";
  options = {
    url: url,
    json: true
  };
  return request.get(options, function(err, res, data) {
    if (err == null) {
      return callback(err, data);
    }
  });
};


/*
history {market:'hs',code:'159915',year:'2016',type:'week'}, (err,json)->
  console.log json unless err?
 */

module.exports = history;

//# sourceMappingURL=json126.js.map
