// Generated by CoffeeScript 1.10.0
var history, recode, ref, request, restring;

request = require('request');

ref = require('secode'), recode = ref.recode, restring = ref.restring;


/* param:
      market: 默認 hs--滬深
      symbol: 代碼
      year: 年份
      type: day,week,month
 */

history = function(param, callback) {
  var c, options, url;
  c = recode(param.symbol, 6);
  url = "http://img1.money.126.net/data/" + param.market + "/kline/" + param.type + "/history/" + param.year + "/" + c + ".json";
  options = {
    url: url,
    json: true
  };
  return request.get(options, function(err, res, json) {
    var array2obj, data, each;
    if (err == null) {
      array2obj = function(arr) {
        var d;
        d = arr[0];
        return {
          時: new Date(d.slice(0, 4) + "-" + d.slice(4, 6) + "-" + d.slice(6)),
          開: arr[1],
          低: arr[2],
          高: arr[3],
          收: arr[4],
          量: arr[5],
          幅: arr[6]
        };
      };
      data = (function() {
        var i, len, ref1, results;
        ref1 = json.data;
        results = [];
        for (i = 0, len = ref1.length; i < len; i++) {
          each = ref1[i];
          results.push(array2obj(each));
        }
        return results;
      })();
      json.data = data;
      return callback(err, json);
    }
  });
};

module.exports = history;


/* 在這行前面加或去一個#就可以測試,測試完記得加回去
history {market:'hs',symbol:'159915',year:'2016',type:'day'}, (err,json)->
  console.log json unless err?
 */

//# sourceMappingURL=json126.js.map
