// Generated by CoffeeScript 1.10.0
var history, recode, ref, request, restring;

request = require('request');

ref = require('secode'), recode = ref.recode, restring = ref.restring;


/* param:
      market: 默認 hs--滬深
      symbol: 代碼
      year: 年份
      type: day,week,month
 */

history = function(param, callback) {
  var c, host, options, scale, url;
  scale = {
    m05: 5,
    m15: 15,
    m30: 30,
    m60: 60,
    day: 60 * 4,
    week: 60 * 4 * 5
  };
  c = recode(param.symbol, 1);
  host = "http://money.finance.sina.com.cn/quotes_service/api/json_v2.php";
  url = host + "/CN_MarketData.getKLineData?symbol=" + c + "&scale=" + scale[param.type] + "&datalen=" + param.len;
  options = {
    url: url,
    json: true
  };
  return request.get(options, function(err, res, data) {
    if (err == null) {
      return callback(err, data);
    }
  });
};

module.exports = history;

//# sourceMappingURL=jsonsina.js.map
