// Generated by CoffeeScript 1.10.0

/*
 Copyright(c) 2016- Jigme Ko <jigme1968@gmail.com>
 MIT Licensed
 */

/* 目的
  Python資源眾多, Pandas有用.
  如何交互收發信息 [參閱](https://github.com/extrabacon/python-shell/issues/16)

  經過測試, tushare 庫 有一個 _write_head() _write_tips() 和 _write_console()
  會污染stdout, 文件為: tushare/stock/cons.py, 須將這些function 全部 加 pass 註釋掉代碼
 */
var Pysh, options, pysh, tsdata;

Pysh = require('python-shell');

options = {
  mode: 'json',
  pythonOptions: ['-u']
};

pysh = new Pysh('./getjson.py', options);

pysh.done = function() {
  return pysh.end(function(err) {
    if (err) {
      throw err;
    }
    return console.info('done.');
  });
};

tsdata = function(command, callback) {
  pysh.on('message', function(json) {
    return callback(pysh, json);
  });
  return pysh.send(command);
};

module.exports = tsdata;

//# sourceMappingURL=tsdata.js.map
